// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "InteractiveInterface.h"

void InteractiveInterface::cb_Load_i(Fl_Button*, void*) {
  const char *strBack = fl_file_chooser("Scene name?", "*.sc", strSceneName.c_str() );

if ( strBack ) {
    interactiveUI.readScene( strBack );
    strSceneName = strBack;
}
RedrawWindow();
}
void InteractiveInterface::cb_Load(Fl_Button* o, void* v) {
  ((InteractiveInterface*)(o->parent()->user_data()))->cb_Load_i(o,v);
}

void InteractiveInterface::cb_m_bLighting_i(Fl_Check_Button*, void*) {
  RedrawWindow();
}
void InteractiveInterface::cb_m_bLighting(Fl_Check_Button* o, void* v) {
  ((InteractiveInterface*)(o->parent()->user_data()))->cb_m_bLighting_i(o,v);
}

void InteractiveInterface::cb_m_bInteractive_i(Fl_Check_Button*, void*) {
  RedrawWindow();
}
void InteractiveInterface::cb_m_bInteractive(Fl_Check_Button* o, void* v) {
  ((InteractiveInterface*)(o->parent()->user_data()))->cb_m_bInteractive_i(o,v);
}

void InteractiveInterface::cb_m_bIBar_i(Fl_Check_Button*, void*) {
  RedrawWindow();
}
void InteractiveInterface::cb_m_bIBar(Fl_Check_Button* o, void* v) {
  ((InteractiveInterface*)(o->parent()->user_data()))->cb_m_bIBar_i(o,v);
}

void InteractiveInterface::cb_m_bIBarHelp_i(Fl_Check_Button*, void*) {
  RedrawWindow();
}
void InteractiveInterface::cb_m_bIBarHelp(Fl_Check_Button* o, void* v) {
  ((InteractiveInterface*)(o->parent()->user_data()))->cb_m_bIBarHelp_i(o,v);
}

void InteractiveInterface::cb_m_bWidget_i(Fl_Check_Button*, void*) {
  RedrawWindow();
}
void InteractiveInterface::cb_m_bWidget(Fl_Check_Button* o, void* v) {
  ((InteractiveInterface*)(o->parent()->user_data()))->cb_m_bWidget_i(o,v);
}

Fl_Double_Window* InteractiveInterface::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = m_interactiveWindow = new Fl_Double_Window(315, 190, "Interactive UI");
    w = o;
    o->user_data((void*)(this));
    { Fl_Button* o = new Fl_Button(5, 5, 100, 25, "Load scene");
      o->callback((Fl_Callback*)cb_Load);
    }
    { Fl_Check_Button* o = m_bLighting = new Fl_Check_Button(115, 5, 25, 25, "Lighting");
      o->down_box(FL_DOWN_BOX);
      o->value(1);
      o->callback((Fl_Callback*)cb_m_bLighting);
    }
    { Fl_Check_Button* o = m_bInteractive = new Fl_Check_Button(210, 5, 25, 25, "Interactive");
      o->down_box(FL_DOWN_BOX);
      o->value(1);
      o->callback((Fl_Callback*)cb_m_bInteractive);
    }
    { Fl_Output* o = m_txtStatus = new Fl_Output(5, 90, 305, 95, "Status");
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Check_Button* o = m_bIBar = new Fl_Check_Button(210, 30, 25, 25, "IBar");
      o->down_box(FL_DOWN_BOX);
      o->callback((Fl_Callback*)cb_m_bIBar);
    }
    { Fl_Check_Button* o = m_bIBarHelp = new Fl_Check_Button(255, 30, 25, 25, "Help");
      o->down_box(FL_DOWN_BOX);
      o->callback((Fl_Callback*)cb_m_bIBarHelp);
    }
    { Fl_Check_Button* o = m_bWidget = new Fl_Check_Button(108, 60, 25, 25, "Widget");
      o->down_box(FL_DOWN_BOX);
      o->value(1);
      o->callback((Fl_Callback*)cb_m_bWidget);
    }
    { Fl_Check_Button* o = m_bWidgetMove = new Fl_Check_Button(183, 60, 25, 25, "Move with widget");
      o->down_box(FL_DOWN_BOX);
      o->value(1);
      o->shortcut(0x40077);
    }
    o->end();
    o->resizable(o);
  }
  return w;
}

InteractiveInterface::InteractiveInterface() {
  m_interactiveWindow = make_window();
strSceneName = "../data/scenes/bujans_raquel.sc";
interactiveUI.setUI( this );
}

UIInterface * InteractiveInterface::getUI() {
  return &interactiveUI;
}
