// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "SceneviewInterface.h"

void SceneviewInterface::cb_Load_i(Fl_Button*, void*) {
  const char *strBack = fl_file_chooser("Scene name?", "*.sc", strSceneName.c_str() );

if ( strBack ) {
    sceneviewUI.readScene( strBack );
    strSceneName = strBack;
}
RedrawWindow();
}
void SceneviewInterface::cb_Load(Fl_Button* o, void* v) {
  ((SceneviewInterface*)(o->parent()->user_data()))->cb_Load_i(o,v);
}

void SceneviewInterface::cb_m_bLighting_i(Fl_Check_Button*, void*) {
  RedrawWindow();
}
void SceneviewInterface::cb_m_bLighting(Fl_Check_Button* o, void* v) {
  ((SceneviewInterface*)(o->parent()->user_data()))->cb_m_bLighting_i(o,v);
}

void SceneviewInterface::cb_m_bInteractive_i(Fl_Check_Button*, void*) {
  RedrawWindow();
}
void SceneviewInterface::cb_m_bInteractive(Fl_Check_Button* o, void* v) {
  ((SceneviewInterface*)(o->parent()->user_data()))->cb_m_bInteractive_i(o,v);
}

void SceneviewInterface::cb_m_bIBar_i(Fl_Check_Button*, void*) {
  RedrawWindow();
}
void SceneviewInterface::cb_m_bIBar(Fl_Check_Button* o, void* v) {
  ((SceneviewInterface*)(o->parent()->user_data()))->cb_m_bIBar_i(o,v);
}

void SceneviewInterface::cb_m_bIBarHelp_i(Fl_Check_Button*, void*) {
  RedrawWindow();
}
void SceneviewInterface::cb_m_bIBarHelp(Fl_Check_Button* o, void* v) {
  ((SceneviewInterface*)(o->parent()->user_data()))->cb_m_bIBarHelp_i(o,v);
}

Fl_Double_Window* SceneviewInterface::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = m_sceneviewWindow = new Fl_Double_Window(310, 165, "Sceneview UI");
    w = o;
    o->user_data((void*)(this));
    { Fl_Button* o = new Fl_Button(5, 5, 100, 25, "Load scene");
      o->callback((Fl_Callback*)cb_Load);
    }
    { Fl_Check_Button* o = m_bLighting = new Fl_Check_Button(125, 5, 25, 25, "Lighting");
      o->down_box(FL_DOWN_BOX);
      o->value(1);
      o->callback((Fl_Callback*)cb_m_bLighting);
    }
    { Fl_Check_Button* o = m_bInteractive = new Fl_Check_Button(210, 5, 25, 25, "Interactive");
      o->down_box(FL_DOWN_BOX);
      o->value(1);
      o->callback((Fl_Callback*)cb_m_bInteractive);
    }
    { Fl_Output* o = m_txtStatus = new Fl_Output(5, 60, 300, 100, "Status");
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Check_Button* o = m_bIBar = new Fl_Check_Button(210, 30, 25, 25, "IBar");
      o->down_box(FL_DOWN_BOX);
      o->value(1);
      o->callback((Fl_Callback*)cb_m_bIBar);
    }
    { Fl_Check_Button* o = m_bIBarHelp = new Fl_Check_Button(260, 30, 25, 25, "Help");
      o->down_box(FL_DOWN_BOX);
      o->callback((Fl_Callback*)cb_m_bIBarHelp);
    }
    o->end();
    o->resizable(o);
  }
  return w;
}

SceneviewInterface::SceneviewInterface() {
  m_sceneviewWindow = make_window();
strSceneName = "../data/scenes/bujans_raquel.sc";
sceneviewUI.setUI( this );
}

UIInterface * SceneviewInterface::getUI() {
  return &sceneviewUI;
}
